#!/usr/bin/env bash
# MANSUN 로컬 DB 초기화: 소유자 롤(migrations) + 앱 롤(RLS 적용) + DB 생성
set -euo pipefail
PGHOST="${PGHOST:-localhost}"
PGPORT="${PGPORT:-5432}"
ADMIN_DB="${ADMIN_DB:-postgres}"
DB_NAME="${DB_NAME:-mansun}"
OWNER_ROLE="${OWNER_ROLE:-mansun_owner}"
OWNER_PW="${OWNER_PW:-mansun_owner}"
APP_ROLE="${APP_ROLE:-mansun_app}"
APP_PW="${APP_PW:-mansun_app}"

psql -h "$PGHOST" -p "$PGPORT" -d "$ADMIN_DB" -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$OWNER_ROLE') THEN
    CREATE ROLE $OWNER_ROLE LOGIN PASSWORD '$OWNER_PW';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$APP_ROLE') THEN
    CREATE ROLE $APP_ROLE LOGIN PASSWORD '$APP_PW';
  END IF;
END \$\$;
SQL

if ! psql -h "$PGHOST" -p "$PGPORT" -d "$ADMIN_DB" -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  psql -h "$PGHOST" -p "$PGPORT" -d "$ADMIN_DB" -v ON_ERROR_STOP=1 -c "CREATE DATABASE $DB_NAME OWNER $OWNER_ROLE;"
fi

psql -h "$PGHOST" -p "$PGPORT" -d "$DB_NAME" -v ON_ERROR_STOP=1 <<SQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER SCHEMA public OWNER TO $OWNER_ROLE;
GRANT CONNECT ON DATABASE $DB_NAME TO $APP_ROLE;
GRANT USAGE ON SCHEMA public TO $APP_ROLE;
ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_ROLE IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_ROLE;
ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_ROLE IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_ROLE;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $APP_ROLE;
SQL
echo "DB '$DB_NAME' ready. owner=$OWNER_ROLE app=$APP_ROLE"
